### ISSUE TITLE
Can it be deployed without virtual env? 

### ISSUE THREAD

**Issue by dinjojo** [krishnakuruvadi/portfoliomanager#12]

**Comment by krishnakuruvadi** [comment]
Virtual environment is a preferred way for python.  You should be able to install without it as well

**Comment by dinjojo** [comment]
Thank you if you can create docker image then it would be cool

**Comment by dinjojo** [comment]
Just on arm odroid and get these error


invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for wrapt
  Running setup.py clean for wrapt
  Building wheel for yfinance (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/portfoliomanager/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kzem0gj/yfinance/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kzem0gj/yfinance/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-j1tsfp7o
       cwd: /tmp/pip-install-8kzem0gj/yfinance/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help

  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for yfinance
----------------------------------------
  ERROR: Failed building wheel for yfinance
  Running setup.py clean for yfinance
Successfully built lazy-object-proxy
Failed to build bs4 dateutils django-solo feedfinder2 huey jieba3k mftool multitasking nltk robin-stocks rope sgmllib3k tinysegmenter Twisted wrapt yfinance
Installing collected packages: asgiref, six, lazy-object-proxy, wrapt, astroid, attrs, txaio, idna, hyperlin

**Comment by dinjojo** [comment]
Any update ?

**Comment by krishnakuruvadi** [comment]
You should open these two in two different terminals.  I tried to get it dockerized but wasnt able to finish it.  I have put the code in the branch dockerize.  I would appreciate if you can try that and fix any issues

**Comment by lal309** [comment]
@dinjojo this application is now dockerized. If that is your preferred deployment method, please see the main branch and follow the instructions in the README.
